#!/bin/bash

# Copyright (C) 2012 Kevin Pulo and the Australian National University.
#
# This file is part of modext.
# 
# modext is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# modext is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with modext.  If not, see <http://www.gnu.org/licenses/>.




for good_group in $(groups); do
runtest -name "good-$good_group" -commands "
package-access-group $good_group
" -results '
expect-audit-success
expect-load-success
no-change
'
done



bgi=0
while groups | grep -s -q "badgroup$bgi"; do
	bgi="$(($i+1))"
done
bad_group="badgroup$bgi"

runtest -name "bad-$bad_group" -commands "
package-access-group $bad_group
" -results '
expect-audit-success
expect-load-fail
expect-noisy-module
'

