#!/bin/bash

# Copyright (C) 2012 Kevin Pulo and the Australian National University.
#
# This file is part of modext.
# 
# modext is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# modext is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with modext.  If not, see <http://www.gnu.org/licenses/>.




runtest -name "1" -commands '
preload-lib libsomething.so
' -results '
before-previous-paths LD_PRELOAD /apps/package/version/libsomething.so
no-change-except LD_PRELOAD
'

runtest -name "2" -commands '
preload-lib lib/libsomething.so
' -results '
before-previous-paths LD_PRELOAD /apps/package/version/lib/libsomething.so
no-change-except LD_PRELOAD
'

runtest -name "3" -commands '
preload-lib libsomething.so
preload-lib lib/libsomejunk.so
preload-lib else/libother.so
' -results '
before-previous-paths LD_PRELOAD /apps/package/version/else/libother.so /apps/package/version/lib/libsomejunk.so /apps/package/version/libsomething.so
no-change-except LD_PRELOAD
'



