# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

# This dumb junk.  Hand-created, since extensions.tcl uses variables that are only defined inside modules.

#puts stderr "ticket to freedom?"
#puts stderr "modulefilename is $ModulesCurrentModulefile"
#puts stderr "modulefilename is $::ModulesCurrentModulefile"

#package ifneeded modext 1.0 [list]
#source [file join $dir extensions.tcl]

#package ifneeded modext 1.0 [list source [file join $dir extensions.tcl]]
#package ifneeded modext 1.0 [list set extensions_home $dir \; source [file join $dir description.tcl]]
package ifneeded modext 0.1 [list source [file join $dir description.tcl]]

